/**
 * @title Foraging Test
 * @description A test experiment for the ForagingPatchPlugin (v7 + Popmotion v11)
 * @version 0.5
 *
 * @imageDir images/foraging-test
 * @audioDir media/audio/sounds
 */

import { initJsPsych } from "jspsych";
import HtmlKeyboardResponsePlugin from "@jspsych/plugin-html-keyboard-response";
import FullscreenPlugin from "@jspsych/plugin-fullscreen";
import ForagingPatchPlugin from "./ForagingPatchPlugin"; 
import { JitteredGridCoordinates } from "./util/PositionGenerators";
import { Scaler } from "./util/Scaler";

/**
 * Helper: Expands a high-level config (like 'targets') into a list of concrete objects
 * with specific X/Y coordinates generated by the JitteredGridCoordinates utility.
 */
function expandConfigToElements(config: any, width: number, height: number) {
    const expandedElements: any[] = [];
    const generator = config.positions;
    const amount = config.amount || 1;

    // Reset generator if applicable
    if (generator && generator.reset) {
        generator.reset();
    }

    for (let i = 0; i < amount; i++) {
        // 1. Get coordinates from generator, or fallback to random
        let pos: { x: number | undefined; y: number | undefined } | undefined = { x: undefined, y: undefined };
        
        if (generator) {
            pos = generator.next(); 
            // Handle if generator runs out of spots
            if (!pos) pos = { x: Math.random() * width, y: Math.random() * height };
        } else {
             pos = { x: Math.random() * width, y: Math.random() * height };
        }

        // 2. Pick a random image from the list
        const imgIndex = Math.floor(Math.random() * config.images.length);
        const image = config.images[imgIndex];
        
        // 3. Create the concrete element config
        const element = {
            id: `${config.type}-${i}`,
            type: config.type,
            image: image,
            x: pos.x,
            y: pos.y,
            width: 50, // Default size
            height: 50,
            collectible: config.collectible,
            points: config.points,
            
            // Sounds
            click_sounds: config.click_sounds,
            mouseover_sounds: config.mouseover_sounds,
            
            // Interaction visuals
            mouseover_image: config.mouseover_images ? config.mouseover_images[imgIndex] : null,
            collected_image: config.collected_images ? config.collected_images[imgIndex] : null,

            // Animation (Passed as config object for Popmotion v11)
            animation: config.animation
        };

        expandedElements.push(element);
    }
    return expandedElements;
}

/**
 * Main Timeline Creation
 */
export function createTimeline(jatosStudyInput: any = null) {

  // Initialize jsPsych (needed for randomization functions)
  const jsPsych = initJsPsych({
    on_finish: () => {
      // jsPsych.data.displayData();
    }
  });

  // This part is related to keeping track of the points. We register these functions with the plugin and
  // the plugin calls them as the participant forages.
  let point_counter = 0;
  function update_point_counter(val: number) {
    point_counter += val;
  }
  function readout_point_counter() {
    return point_counter;
  }

  // Initialize timeline
  const timeline: any[] = [];

  // Welcome screen
  timeline.push({
    type: HtmlKeyboardResponsePlugin,
    stimulus: "<p>Welcome to the foraging test!</p><p>Press any key to begin.</p>",
  });

  // Switch to fullscreen
  timeline.push({
    type: FullscreenPlugin,
    fullscreen_mode: true,
  });

  // This will define an object that will be used to
  // generate positions for targets and distractors
  const stim_positions = new JitteredGridCoordinates({
    columns: 12,
    rows: 7,
    hspacing: 150,
    vspacing: 130,
    hjitter: 10,
    vjitter: 10,
    hoffset: 0,
    voffset: 80,
    on_used_up: "nothing",
    on_patch_done: "reset",
  });

  // Let's setup another random position generator for the clouds
  const cloud_positions = new JitteredGridCoordinates({
    columns: 5,
    rows: 1,
    hspacing: 300,
    vspacing: 0,
    hjitter: 30,
    vjitter: 0,
    hoffset: 0,
    voffset: -550,
    on_used_up: "nothing",
    on_patch_done: "reset",
  });

  ///////// In this part, we describe the patches //////////

  // For each different element type, we create a variable with the following entries ...
  // (let's start with the targets):
  const targetConfig = {
    type: "target", // This is the name of the element type
    amount: 20, // Here we specify how many elements of that type a patch contains
    positions: stim_positions, // A position generator that is used to place the elements
    images: ["butterfly1.png", "butterfly2.png"], // Here is a list of alternative images for this type
    mouseover_images: ["flower1.png", "flower2.png"], // Images shown at "mouseover"
    collected_images: ["collected.png", "collected.png"], // Images shown when collected
    
    // Sound settings
    click_sounds: ["beep.mp3"], 
    mouseover_sounds: ["click.mp3"], 
    
    collectible: true, // If collectible is true, then the objects disappear on click
    points: 10, // Points added to the overall score for collecting this type of elements
  };

  // Now we do the same for distractors
  const distractorConfig = {
    type: "distractor",
    amount: 20,
    positions: stim_positions, // Note that this is the same position generator object as above
    images: ["flower1.png", "flower2.png"],
    
    collectible: true, // In new logic, distractors are often 'collectible' but yield negative points
    points: -20, // Negative points for clicking a distractor!
    
    // Animation: Wiggle effect (Native Popmotion v11 Config)
    animation: {
      from: { rotate: -10, x: -5 },
      to: { rotate: 10, x: 5 },
      duration: 1000,
      elapsed: Math.floor(Math.random() * 1000.0),
      repeat: Infinity,
      repeatType: "mirror" // Replaces 'flip' in v11
    },
  };

  // Let's get some clouds as decorations
  const cloudConfig = {
    type: "clouds",
    amount: 3,
    positions: cloud_positions,
    images: ["cloud1.png", "cloud2.png", "cloud3.png", "cloud4.png"],
    collectible: false,
    points: 0,
    
    // Animation: Drifting Clouds (Native Popmotion v11 Config)
    animation: { 
        from: { x: -200 }, 
        to: { x: 2120 }, // Move from left buffer to right buffer
        duration: 40000, // 40 seconds to cross
        repeat: Infinity,
        ease: "linear"
    }, 
  };

  // -- Timeline Variables and Trial Generation --
  
  const patchWidth = 1920;
  const patchHeight = 1080;

  // Generate the concrete list of items for the plugin
  // Note: We combine all element types into one flat array here
  const elementsList = [
      ...expandConfigToElements(targetConfig, patchWidth, patchHeight),
      ...expandConfigToElements(distractorConfig, patchWidth, patchHeight),
      ...expandConfigToElements(cloudConfig, patchWidth, patchHeight)
  ];

  // This will setup a factorial design
  const factors = {
    timeout: [50000, 100000], // Brief collecting period and long
  };

  const repetitions = 2; // The number of repetitions of each cell of the design
  const full_design = jsPsych.randomization.factorial(factors, repetitions);

  // This will create the actual patches of the experiment:
  const foraging_trial = {
    type: ForagingPatchPlugin, // Tells jsPsych to use our foraging plugin
    images_path: "media/images/foraging-test/", 
    audio_path: "media/audio/sounds",
    patch_size: [1920, 1080],
    
    // Pass the functions for scoring
    point_counter_update_function: update_point_counter,
    point_counter_read_out_function: readout_point_counter,

    // Parameters mapped from timeline variables
    timeout: jsPsych.timelineVariable('timeout'),
    
    // Using the generated list
    elements: elementsList, 
    
    // Backgrounds (plugin handles random selection from array)
    background: ["background1.svg", "background2.svg", "background3.svg"], 

    points_display_html: "<div style='font-size:24px; font-weight:bold; color:#99AAFF;'>Points: <span id='jspsych-foraging-score-value'>0</span></div>",
    
    next_patch_click_html: "<div id='next-patch-click-html' class='next-click' style='cursor:pointer;'><font size=+4 face='Comic Sans MS' color='#99AAFF'> Next </font></div>",
    
    travel_time: 4000,
    
    // New plugin uses boolean for standard fade animation
    patch_leaving_animation: true,
    trial_ends_when_all_collected: true,

    // This is required to scale the display to fit the (unknown) screen size
    on_load: () => {
       const container = document.getElementById("jspsych-foraging-container");
       if(container) {
         new Scaler(container, 1920, 1080, 0);
       }
    },
  };

  // As usual in jsPsych: push the trials into the timeline
  timeline.push({
    timeline: [foraging_trial],
    timeline_variables: full_design,
  });

  return timeline;
}